# ======================
# 1. Dependencias DEV
# ======================
FROM node:22-alpine AS deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

# ======================
# 2. Builder
# ======================
FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
ARG ORDERS_DATABASE_URL
ENV DATABASE_URL=${ORDERS_DATABASE_URL}

#Imprimir el arg para ver el valora recibido
RUN echo "database_url ::: ${ORDERS_DATABASE_URL}}";

RUN npx prisma generate
RUN npx prisma migrate deploy

RUN npm run build

# ======================
# 3. Dependencias PROD (separado del build)
# ======================
FROM node:22-alpine AS prod-deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev

# ======================
# 4. Producción
# ======================
FROM node:22-alpine AS prod
WORKDIR /usr/src/app

COPY --from=prod-deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/generated ./generated 
COPY --from=build /usr/src/app/prisma ./prisma

ENV NODE_ENV=production
USER node
CMD [ "node", "dist/src/main.js" ]